<a href="https://colab.research.google.com/github/moch1996/MachineLearningProj/blob/master/assignment_03_a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manipulate PyTorch Tensors
<hr>

## Matrix manipulation

In [2]:
import torch
import numpy as np

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [8]:

# write your code here

A = torch.FloatTensor([[1,2],[3,4]])
B = torch.mul(A,10)
C = torch.add(A,B)

# print
print(A)
print('')
print(B)
print('')
print(C)

tensor([[1., 2.],
        [3., 4.]])

tensor([[10., 20.],
        [30., 40.]])

tensor([[11., 22.],
        [33., 44.]])


### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [9]:

# write your code here

print(A.dim() )    # print the dimension of the matrix A
print('')
print(A.size() )    # print the size of the matrix A
print('')
print(A.type())    # print the type of the matrix A

2

torch.Size([2, 2])

torch.FloatTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [10]:

# write your code here

A_long = torch.as_tensor(A,dtype=torch.int64)

print(A_long.type() )    # print the type of A_long
print('')
print(A.type() )    # print the type of A

torch.LongTensor

torch.FloatTensor


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [28]:

# write your code here

A = torch.rand(5,2,3)

print(A)
print(A.type() )    # print the type of A
print(A.dim() )    # print the dimension of A
print(A.size() )    # print the size of A
#print(A[:,1,:])
#print(A[,:,].size() )    # print the size of the middle (second) dimension

SyntaxError: ignored

### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [29]:

# write your code here

A = torch.zeros(2,3,4,5)

print(A)


tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
