<a href="https://colab.research.google.com/github/moch1996/MachineLearningProj/blob/master/assignment_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('data-kmeans.csv')
data = dataset.values


In [16]:
def compute_distance(a,b) :
  dist = np.sqrt((a[0] - b[0])**2 + (a[1]-b[1])**2)
  return dist

In [27]:
c = np.array([[1],[2]])
d = np.array([[3],[4]])

In [28]:
compute_distance(c,d)

array([2.82842712])

In [ ]:
def compute_centroid(Z):

    center = np.ones((1,2))
    center[0,0] = np.sum(Z[1]) 
    return center


In [43]:
k = np.ones((1,2))
k[0,0] = 6
k[0,1] = 3
k

array([[6., 3.]])

In [53]:
Z = np.array([[1,2],[2,3],[4,5]])
print(Z)
print(np.sum(Z[:,0]))

[[1 2]
 [2 3]
 [4 5]]
7
